class Setting(object):
    pass

PARALLEL = Setting()
PARALLEL.JOBS = -1
PARALLEL.JOBLIB_VERBOSE = 0
PARALLEL.JOBLIB_PRE_DISPATCH = 'n_jobs'
PARALLEL.PMAP = False

GAP_STATISTIC = Setting()
GAP_STATISTIC.RANDOMIZED_PCA_THRESHOLD = 10
GAP_STATISTIC.NUM_CLUSTERS_WITHOUT_IMPROVEMENT = 5
GAP_STATISTIC.MAXIMUM_DECLINE = 0.5
